
# Задание 1. NotFoundException (обязательное к выполнению)

Вы развиваете приложение с менеджером товаров, который мы рассматривали на лекции, и решили сделать так, чтобы при попытке удаления несуществующего объекта из репозитория генерировалось ваше исключение, а не `ArrayIndexOfBoundsException`.

Обратите внимание: это правильный подход, поскольку таким образом вы сообщаете (через генерацию исключения), что это исключение, вписывающееся в вашу логику, а не является ошибкой программиста.

Что нужно сделать:
1. Возьмите проект (мы его писали в рамках дз про наследование) с менеджером, репозиторием и товарами.
1. Создайте класс исключения `NotFoundException` отнаследовавшись от `RuntimeException` и реализуйте как минимум конструктор с параметром-сообщением (он будет просто вызывать супер-конструктор предка, см. подсказку)
1. В методе удаления `removeById` сначала проверяйте, есть ли элемент (для этого прямо из метода `removeById` вызывайте метод `findById` (про него ниже): если результат - `null`, тогда выкидывайте исключение `NotFoundException`)
1. Напишите 2 автотеста на репозиторий: первый должен проверять успешность удаления существующего элемента, второй - генерации `NotFoundException` при попытке удаления несуществующего элемента

# Задание 2*. AlreadyExistsException (НЕобязательная задача)

В том же самом проекте и в той же самой ветке добавьте следующую новую функциональность. В методе добавления нового товара в репозиторий должна осуществляться проверка на то, что в нём нет уже товара, у которого бы совпадал `id` с `id` добавляемого товара. Если же такой уже есть, то должно выкидываться ваше исключение - 
`AlreadyExistsException`. 

Напишите 2 автотеста на репозиторий: первый должен проверять успешность добавления элемента, второй - генерации `AlreadyExistsException` при попытке добавить элемент с повторяющимся `id`.

Итого: отправьте на проверку ссылку на гитхаб-репозиторий с вашим проектом. 